"""initial schema

Revision ID: a1b5ea75d9f9
Revises: 
Create Date: 2026-07-23 10:29:53.268340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b5ea75d9f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('centre_code', sa.String(length=20), nullable=False),
    sa.Column('centre_name', sa.String(length=255), nullable=True),
    sa.Column('centre_head', sa.String(length=255), nullable=True),
    sa.Column('centre_city', sa.String(length=255), nullable=True),
    sa.Column('exam_year', sa.Integer(), nullable=True),
    sa.Column('exam_name_x', sa.String(length=120), nullable=True),
    sa.Column('exam_name_xii', sa.String(length=120), nullable=True),
    sa.Column('exam_fullname_x', sa.String(length=255), nullable=True),
    sa.Column('exam_fullname_xii', sa.String(length=255), nullable=True),
    sa.Column('paper_size', sa.String(length=20), nullable=True),
    sa.Column('colour_theme', sa.String(length=20), nullable=True),
    sa.Column('include_citation', sa.Boolean(), nullable=True),
    sa.Column('rows', sa.Integer(), nullable=True),
    sa.Column('cols', sa.Integer(), nullable=True),
    sa.Column('class_order', sa.String(length=20), nullable=True),
    sa.Column('split', sa.String(length=20), nullable=True),
    sa.Column('sep_plan', sa.Boolean(), nullable=True),
    sa.Column('show_vacant', sa.Boolean(), nullable=True),
    sa.Column('incl_private', sa.Boolean(), nullable=True),
    sa.Column('seat_dir', sa.String(length=20), nullable=True),
    sa.Column('stagger', sa.Boolean(), nullable=True),
    sa.Column('x_datesheet', sa.JSON(), nullable=True),
    sa.Column('xii_datesheet', sa.JSON(), nullable=True),
    sa.Column('x_codes', sa.JSON(), nullable=True),
    sa.Column('xii_codes', sa.JSON(), nullable=True),
    sa.Column('inv_req', sa.JSON(), nullable=True),
    sa.Column('qp_log', sa.JSON(), nullable=True),
    sa.Column('ab_next_type_id', sa.Integer(), nullable=True),
    sa.Column('ab_next_receipt_id', sa.Integer(), nullable=True),
    sa.Column('ab_next_exception_id', sa.Integer(), nullable=True),
    sa.Column('ab_next_audit_id', sa.Integer(), nullable=True),
    sa.Column('saved_at', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('centre_code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ab_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ab_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('short_code', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('roll', sa.String(length=20), nullable=False),
    sa.Column('class', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('mother', sa.String(length=255), nullable=True),
    sa.Column('father', sa.String(length=255), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('cat', sa.String(length=20), nullable=True),
    sa.Column('school_code', sa.String(length=20), nullable=True),
    sa.Column('school_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'roll', name='uq_candidate_session_roll')
    )
    op.create_table('date_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exam_date', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('split', sa.String(length=20), nullable=True),
    sa.Column('class_order', sa.String(length=20), nullable=True),
    sa.Column('subject_order', sa.JSON(), nullable=True),
    sa.Column('locked_at', sa.BigInteger(), nullable=True),
    sa.Column('generated_at', sa.BigInteger(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'exam_date', name='uq_datestate_session_date')
    )
    op.create_table('ab_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_state_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('serial_raw', sa.String(length=40), nullable=False),
    sa.Column('assigned_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['date_state_id'], ['date_states.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['ab_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ab_damaged_serials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_state_id', sa.Integer(), nullable=False),
    sa.Column('serial_raw', sa.String(length=40), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('damaged_at', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['date_state_id'], ['date_states.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['ab_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ab_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exam_date', sa.String(length=20), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('start_serial', sa.String(length=40), nullable=False),
    sa.Column('end_serial', sa.String(length=40), nullable=False),
    sa.Column('challan_no', sa.String(length=60), nullable=True),
    sa.Column('challan_qty', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['ab_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ab_subject_type_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('class', sa.String(length=5), nullable=False),
    sa.Column('subject_code', sa.String(length=10), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['ab_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ab_supp_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_state_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('serial_raw', sa.String(length=40), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.BigInteger(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['date_state_id'], ['date_states.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['ab_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ab_supp_class_type_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('class', sa.String(length=5), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['ab_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ab_supp_damaged_serials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_state_id', sa.Integer(), nullable=False),
    sa.Column('serial_raw', sa.String(length=40), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('damaged_at', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['date_state_id'], ['date_states.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['ab_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_state_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('marked_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['date_state_id'], ['date_states.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date_state_id', 'candidate_id', name='uq_attendance_datestate_candidate')
    )
    op.create_table('candidate_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('exam_date', sa.String(length=20), nullable=False),
    sa.Column('subject_code', sa.String(length=10), nullable=False),
    sa.Column('subject_name', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seating_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_state_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('room_no', sa.Integer(), nullable=True),
    sa.Column('seat_in_room', sa.Integer(), nullable=True),
    sa.Column('row', sa.Integer(), nullable=True),
    sa.Column('col', sa.Integer(), nullable=True),
    sa.Column('seat_label', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['date_state_id'], ['date_states.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date_state_id', 'candidate_id', name='uq_seating_datestate_candidate')
    )
    op.create_table('ab_receipt_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('serial_raw', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['receipt_id'], ['ab_receipts.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['ab_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ab_receipt_exceptions')
    op.drop_table('seating_assignments')
    op.drop_table('candidate_subjects')
    op.drop_table('attendance')
    op.drop_table('ab_supp_damaged_serials')
    op.drop_table('ab_supp_class_type_map')
    op.drop_table('ab_supp_assignments')
    op.drop_table('ab_subject_type_map')
    op.drop_table('ab_receipts')
    op.drop_table('ab_damaged_serials')
    op.drop_table('ab_assignments')
    op.drop_table('date_states')
    op.drop_table('candidates')
    op.drop_table('ab_types')
    op.drop_table('ab_audit_log')
    op.drop_table('users')
    op.drop_table('sessions')
    # ### end Alembic commands ###
